#ifndef COLOR_CONSTANTS_H
#define COLOR_CONSTANTS_H

struct ColorConstants {
	static Color 
    RED, GREEN, BLUE, 
    DARK_RED, DARK_GREEN, DARK_BLUE,
    LIGHT_RED, LIGHT_GREEN, LIGHT_BLUE,
    YELLOW, CYAN, MAGENTA, 
    DARK_YELLOW, DARK_CYAN, DARK_MAGENTA,
    LIGHT_YELLOW, LIGHT_CYAN, LIGHT_MAGENTA,
    WHITE, BLACK, 
    GREY, DARK_GREY, LIGHT_GREY;
};

#endif
